### ISSUE TITLE
Erreur au démarrage, 

### ISSUE THREAD

**Issue by frett27** [barrelorgandiscovery/aprintproject#101]
Dans le log d'erreur :+1: 
1 ERROR org.barrelorgandiscovery.gui.aprintng.APrintApplication:290 [main]: C:\Program Files (x86)\APrint Studio\aprintstudio\pluginnativelibraries is not a directory.
java.lang.IllegalArgumentException: C:\Program Files (x86)\APrint Studio\aprintstudio\pluginnativelibraries is not a directory.
	at org.barrelorgandiscovery.gui.aprintng.APrintApplication.addToJavaLibraryPath(APrintApplication.java:404)
	at org.barrelorgandiscovery.gui.aprintng.APrintApplication.launch(APrintApplication.java:147)
	at org.barrelorgandiscovery.gui.aprintng.APrintApplication.main(APrintApplication.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.barrelorgandiscovery.gui.aprintng.APrintApplicationBootStrap.main(APrintApplicationBootStrap.java:126)

au démarrage, le répertoire ne peut être créé ou n'existe pas (pas pu être créé à cause des droits windows)

**Comment by frett27** [comment]
fixed, 
ajout d'un test + panneau au démarrage du programme
