### ISSUE TITLE
chargement image model editor

### ISSUE THREAD

**Issue by frett27** [barrelorgandiscovery/aprintproject#104]
0 ERROR org.barrelorgandiscovery.gui.etl.ModelBridge:307 [AWT-EventQueue-0]: error :image cannot be loaded, width or height incorrect
java.lang.Exception: image cannot be loaded, width or height incorrect
	at org.barrelorgandiscovery.tools.ImageTools.loadImage(ImageTools.java:234)
	at org.barrelorgandiscovery.tools.ImageTools.loadImage(ImageTools.java:209)
	at org.barrelorgandiscovery.tools.ImageTools.loadImageIfExists(ImageTools.java:167)
	at org.barrelorgandiscovery.tools.ImageTools.loadIconIfExists(ImageTools.java:196)
	at org.barrelorgandiscovery.gui.etl.ModelBridge.getAssociatedIcon(ModelBridge.java:305)
	at org.barrelorgandiscovery.gui.etl.ModelEditor.<init>(ModelEditor.java:341)

**Comment by frett27** [comment]
passage en warning, il faut savoir sur quelle boite à outils cela se passe
