### ISSUE TITLE
Arret du jeu version 951, sous macos13

### ISSUE THREAD

**Issue by frett27** [barrelorgandiscovery/aprintproject#105]
137841 ERROR org.barrelorgandiscovery.gui.aprintng.APrintNGVirtualBookInternalFrame$APrintVirtualBookFramePlaySubSystemFeedback:3003 [Thread-30]: error in playstopped :null
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1371)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1346)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at org.barrelorgandiscovery.gui.aprintng.APrintNGVirtualBookInternalFrame$APrintVirtualBookFramePlaySubSystemFeedback.informCurrentPlayPosition(APrintNGVirtualBookInternalFrame.java:2958)
	at org.barrelorgandiscovery.playsubsystem.IPlaySubSystemFeedBackWrapper.informCurrentPlayPosition(IPlaySubSystemFeedBackWrapper.java:31)
	at org.barrelorgandiscovery.playsubsystem.GervillPlaySubSystemWithRegisterInstruments$1.run(GervillPlaySubSystemWithRegisterInstruments.java:294)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at org.barrelorgandiscovery.virtualbook.VirtualBook.getLength(VirtualBook.java:471)
	at org.barrelorgandiscovery.gui.aedit.JVirtualBookScrollableComponent.computeIncrementAndUpdateScrollsFromBookAndComponentSize(JVirtualBookScrollableComponent.java:186)
	at org.barrelorgandiscovery.gui.aedit.JVirtualBookScrollableComponent.touchBook(JVirtualBookScrollableComponent.java:233)
	at org.barrelorgandiscovery.gui.aedit.JVirtualBookScrollableComponent.setHightlight(JVirtualBookScrollableComponent.java:359)
	at org.barrelorgandiscovery.gui.aprintng.APrintNGVirtualBookInternalFrame$APrintVirtualBookFramePlaySubSystemFeedback$2.run(APrintNGVirtualBookInternalFrame.java:2984)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)

**Comment by frett27** [comment]
Durcissement de l'arrêt du jeu (une exception est lancée sur le "stop")
