### ISSUE TITLE
Scale component

### ISSUE THREAD

**Issue by frett27** [barrelorgandiscovery/aprintproject#37]
Date:			Sat Mar 06 12:58:15 CET 2021 (1615031895592)
Thread:		AWT-EventQueue-0
Message #:	11
Level:		ERROR
NDC:			
Category:	org.barrelorgandiscovery.gui.ascale.ScaleComponent
Message:		loadscale
Location:	org.barrelorgandiscovery.gui.ascale.ScaleComponent.loadScale(ScaleComponent.java:1058)
Thrown:
java.lang.NullPointerException
	at org.barrelorgandiscovery.gui.ascale.ScaleComponent.loadScale(ScaleComponent.java:1056)
	at org.barrelorgandiscovery.gui.ascale.JEquivalentScaleChooserPanel.initComponents(JEquivalentScaleChooserPanel.java:71)
	at org.barrelorgandiscovery.gui.ascale.JEquivalentScaleChooserPanel.<init>(JEquivalentScaleChooserPanel.java:53)
	at org.barrelorgandiscovery.gui.aprintng.APrintNG$22$2.run(APrintNG.java:1826)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by frett27** [comment]
This don't really touch the using, but needs to be fixed to not pollute the logs and analysis of software analysis
